@startuml

participant "Device App" as D
participant "Service App" as S

title **Pairing**

D -> S: Update reported properties(\n\tserviceInstanceId = None, \n\trequestedServicePool = <poolName>, \n\trunId = <runId>)
note left: Device sets reported properties to request pairing\nwith service in service pool called <poolName>

S -> D: Update desired properties(\n\tserviceInstanceId = <instanceId>, \n\trunId = <runId>)
note right: Service sets desired properties to notify deivce that it is available for pairing

D -> S: Update reported properties(\n\tserviceInstanceId = <instanceId>)
note left: Device sets reported properties to notify service that it accepts the pairing

D -> S: SendMessage(serviceInstanceId = <instanceId>)
note left: Device begins normal operation

@enduml