@startuml
participant "Device App" as D
participant "Service App" as S

title **C2D testing**

D -> S: SetReportedProperties({\n\ttestControl: {\n\t\tc2d: {\n\t\t\tsend: true\n\t\t\tmessageIntervalInSeconds: x\n}}})
note left: Device asks service to start sending\nc2d messages, one every x seconds

S -> D: SendC2d({\n\tcmd: "testC2d"\n\ttestC2dMessageIndex: 1\n})
note right: Service begins sending c2d,\none every x seconds\nwith increasing testC2dMessageIndex values

S -> D: SendC2d({\n\tcmd: "testC2d"\n\ttestC2dMessageIndex: 2\n})
note left: No device response is necessary

S -> D: SendC2d({\n\tcmd: "testC2d"\n\ttestC2dMessageIndex: 3\n})
note left: Device app uses testC2dMessageIndex to \nverify that all messages are recevied.\n\nMissing messages are logged and the \ntest fails if the number of missing \nmessages exceeds the allowed limit.
@enduml