@startuml
participant "Device App" as D
participant "Service App" as S

title **Telemetry Testing**

D -> S: SendTelemetry(\n\tcmd="serviceAckRequest", \n\tserviceInstanceId=<instanceId>, \n\tserviceAckId=<ackId_1>)
note left: device sends multiple telemetry messages to service,\nrequesting a service ack for each

D -> S: SendTelemetry(\n\tcmd="serviceAckRequest", \n\tserviceInstanceId=<instanceId>, \n\tserviceAckId=<ackId_2>)

D -> S: SendTelemetry(\n\tcmd="serviceAckRequest", \n\tserviceInstanceId=<instanceId>, \n\tserviceAckId=<ackId_3>)

S -> D: SendC2d(\n\tcmd="serviceAckResponse", \n\tserviceAcks=[<ackId_1>, <ackId_2>, <ackId_3>])
note right: every 15 seconds, the service sends a serviceAckResponse\nwith the ack IDs received since the last serviceAckResponse

@enduml