ARG BASE
FROM ${BASE}

ARG LIBRARY_VERSION
RUN pip install azure-iot-device==${LIBRARY_VERSION}

COPY container_scripts/_fetch-functions.sh /
COPY container_scripts/fetch-device-secrets.sh /
COPY python/containers/run-device.sh /
COPY python/device/* /device/
COPY python/common/* /common/
RUN pip install -e common

ENTRYPOINT ["/bin/bash", "-v", "/run-device.sh"]
